/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SupplyChainProvenance } from "./SupplyChainProvenance";
export * as factories from "./factories";
export { SupplyChainProvenance__factory } from "./factories/SupplyChainProvenance__factory";
