/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SupplyChainProvenance {
  export type BatchStruct = {
    fileHash: BytesLike;
    startRow: BigNumberish;
    endRow: BigNumberish;
    merkleRoot: BytesLike;
    anchoredAt: BigNumberish;
  };

  export type BatchStructOutput = [
    fileHash: string,
    startRow: bigint,
    endRow: bigint,
    merkleRoot: string,
    anchoredAt: bigint
  ] & {
    fileHash: string;
    startRow: bigint;
    endRow: bigint;
    merkleRoot: string;
    anchoredAt: bigint;
  };
}

export interface SupplyChainProvenanceInterface extends Interface {
  getFunction(
    nameOrSignature: "anchorBatch" | "batchExists" | "getBatch" | "owner"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BatchAnchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorBatch",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "anchorBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
}

export namespace BatchAnchoredEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    fileHash: BytesLike,
    startRow: BigNumberish,
    endRow: BigNumberish,
    merkleRoot: BytesLike,
    anchoredAt: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    fileHash: string,
    startRow: bigint,
    endRow: bigint,
    merkleRoot: string,
    anchoredAt: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    fileHash: string;
    startRow: bigint;
    endRow: bigint;
    merkleRoot: string;
    anchoredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyChainProvenance extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChainProvenance;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainProvenanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorBatch: TypedContractMethod<
    [
      batchId: BigNumberish,
      fileHash: BytesLike,
      startRow: BigNumberish,
      endRow: BigNumberish,
      merkleRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  batchExists: TypedContractMethod<[batchId: BigNumberish], [boolean], "view">;

  getBatch: TypedContractMethod<
    [batchId: BigNumberish],
    [SupplyChainProvenance.BatchStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorBatch"
  ): TypedContractMethod<
    [
      batchId: BigNumberish,
      fileHash: BytesLike,
      startRow: BigNumberish,
      endRow: BigNumberish,
      merkleRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchExists"
  ): TypedContractMethod<[batchId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBatch"
  ): TypedContractMethod<
    [batchId: BigNumberish],
    [SupplyChainProvenance.BatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BatchAnchored"
  ): TypedContractEvent<
    BatchAnchoredEvent.InputTuple,
    BatchAnchoredEvent.OutputTuple,
    BatchAnchoredEvent.OutputObject
  >;

  filters: {
    "BatchAnchored(uint256,bytes32,uint256,uint256,bytes32,uint256)": TypedContractEvent<
      BatchAnchoredEvent.InputTuple,
      BatchAnchoredEvent.OutputTuple,
      BatchAnchoredEvent.OutputObject
    >;
    BatchAnchored: TypedContractEvent<
      BatchAnchoredEvent.InputTuple,
      BatchAnchoredEvent.OutputTuple,
      BatchAnchoredEvent.OutputObject
    >;
  };
}
